"""PDF and JSON report generation for completed rides."""
from __future__ import annotations

import io
import json
import os
from datetime import datetime
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession

from core.database import get_db
from models.ride import Ride

router = APIRouter()


def _build_pdf(ride: Ride) -> bytes:
    """Generate a PDF report using reportlab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        )

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            "Title", parent=styles["Heading1"], fontSize=22, textColor=colors.HexColor("#00D4FF")
        )
        story.append(Paragraph("BikeAI Ride Report", title_style))
        story.append(Spacer(1, 0.4 * cm))

        # Ride ID + date
        story.append(Paragraph(
            f"Ride #{ride.id} — {ride.created_at.strftime('%B %d, %Y %H:%M') if ride.created_at else '—'}",
            styles["Normal"]
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        story.append(Spacer(1, 0.4 * cm))

        # Summary table
        def fmt(v, unit=""):
            return f"{round(v, 1)}{unit}" if v is not None else "—"

        data = [
            ["Metric", "Value"],
            ["Distance", fmt(ride.distance_km, " km")],
            ["Max Speed", fmt(ride.max_speed_kmh, " km/h")],
            ["Avg Speed", fmt(ride.avg_speed_kmh, " km/h")],
            ["Skill Score", fmt(ride.skill_score, " / 100")],
            ["Danger Score", fmt(ride.danger_score, " / 100")],
            ["Safety Rating", ride.safety_rating or "—"],
            ["Aggression Score", fmt(ride.aggression_score, " / 100")],
            ["Accident Probability", f"{round(ride.accident_probability * 100, 1)}%" if ride.accident_probability else "—"],
        ]
        table = Table(data, colWidths=[8 * cm, 8 * cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A1A2E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5F5")]),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.6 * cm))

        # Event counts
        story.append(Paragraph("Behaviour Events", styles["Heading2"]))
        events_data = [["Event Type", "Count"]]
        for field, label in [
            ("hard_brake_count", "Hard Braking"),
            ("hard_accel_count", "Hard Acceleration"),
            ("zigzag_count", "Zig-Zag Riding"),
            ("overtake_count", "Unsafe Overtaking"),
            ("unsafe_distance_count", "Unsafe Distance"),
            ("speed_violation_count", "Speed Violations"),
        ]:
            events_data.append([label, str(getattr(ride, field, 0) or 0)])
        etable = Table(events_data, colWidths=[10 * cm, 6 * cm])
        etable.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#FF4B4B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#FFF0F0")]),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(etable)
        story.append(Spacer(1, 0.6 * cm))

        # Notes
        if ride.notes:
            story.append(Paragraph("Notes", styles["Heading2"]))
            story.append(Paragraph(ride.notes, styles["Normal"]))

        story.append(Spacer(1, 1 * cm))
        story.append(Paragraph(
            f"Generated by BikeAI Analyzer — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            styles["Italic"]
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # Fallback: plain text PDF-like bytes if reportlab unavailable
        content = f"BikeAI Ride Report\nRide #{ride.id}\nSkill: {ride.skill_score}\n"
        return content.encode()


@router.get("/{ride_id}")
async def download_pdf_report(ride_id: int, db: AsyncSession = Depends(get_db)):
    ride = await db.get(Ride, ride_id)
    if not ride:
        raise HTTPException(status_code=404, detail="Ride not found")
    pdf_bytes = _build_pdf(ride)
    filename = f"ride_{ride_id}_report.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/{ride_id}/json")
async def get_json_report(ride_id: int, db: AsyncSession = Depends(get_db)):
    ride = await db.get(Ride, ride_id)
    if not ride:
        raise HTTPException(status_code=404, detail="Ride not found")

    report: Dict[str, Any] = {
        "ride_id": ride.id,
        "title": ride.title,
        "status": ride.status.value if ride.status else None,
        "created_at": ride.created_at.isoformat() if ride.created_at else None,
        "started_at": ride.started_at.isoformat() if ride.started_at else None,
        "ended_at": ride.ended_at.isoformat() if ride.ended_at else None,
        "stats": {
            "distance_km": ride.distance_km,
            "max_speed_kmh": ride.max_speed_kmh,
            "avg_speed_kmh": ride.avg_speed_kmh,
        },
        "scores": {
            "skill_score": ride.skill_score,
            "danger_score": ride.danger_score,
            "safety_rating": ride.safety_rating,
            "aggression_score": ride.aggression_score,
            "accident_probability": ride.accident_probability,
        },
        "events": {
            "hard_brake_count": ride.hard_brake_count,
            "hard_accel_count": ride.hard_accel_count,
            "zigzag_count": ride.zigzag_count,
            "overtake_count": ride.overtake_count,
            "unsafe_distance_count": ride.unsafe_distance_count,
            "speed_violation_count": ride.speed_violation_count,
        },
    }
    return JSONResponse(content=report)
